### ISSUE TITLE
Doesn't work for Lumen 5.2

### ISSUE THREAD

**Issue by mk-relax** [arisro/behat-lumen-extension#2]
This packages does not work for Lumen 5.2, as the Lumen `Application` object does not implement `HttpKernelInterface` anymore... I tried fixing it, but I'm not sure how to do it.

**Comment by pmartelletti** [comment]
@arisro any ideas of why Lumen stopped implementing that Interface? Any workarounds?

**Comment by arisro** [comment]
Can be easily fixed. :)
Will do it sometime in the next 2 days.

**Comment by arisro** [comment]
@mk-relax, @pmartelletti 

v2.0.0 (2c804ae77b797610a30f76603381dcae1ab32117) should be compatible with Lumen 5.2 if you want to give it a try. Please let me know if there are any issues with it. I'm not actively working with Lumen so I have no relevant test cases to test it thoroughly.

They trimmed more code from Lumen to make it even more lightweight. It's funny still that they did this kind of changes in a minor version. :disappointed:

**Comment by mk-relax** [comment]
I tested v2.0.0, but can't get it to work. The error I'm getting is:

```
[ErrorException]
Arisro\Behat\Driver\LumenClient and Laravel\Lumen\Testing\Concerns\MakesHttpRequests
define the same property ($response) in the composition of Arisro\Behat\Driver\LumenClient.
This might be incompatible, to improve maintainability consider using accessor methods in
traits instead. Class was composed
```

BTW I looked at the Lumen code again and although the `HttpKernelInterface` interface was removed, it seems that the methods that implement it were not removed, but just moved to a Trait.

**Comment by RichSelby** [comment]
I've just started using Lumen, so am no expert, but as I'm keen to get this working I had a play around. Interestingly, when I crudely removed the clash from this package, I hit the same issue in the package Symfony\Component\BrowserKit\Client. 
As the LumenClient extends the Symfony\Component\BrowserKit\Client it's a problem right at the core. 

Without getting too bogged down in the detail it appears to me that it's the protected $response declaration in lumen's MakesHttpRequests trait, that has caused the issue.

**Comment by arisro** [comment]
@mk-relax Yes, I noticed that. v2.0.0 uses that trait. But as @RichSelby sais, its the $response attribute that LumenClient declares and conflicts with the $response from the trait.

It's an easy fix, I will try to push it tonight.

**Comment by arisro** [comment]
@mk-relax, @RichSelby

Should be fixed now with 2.0.1 (bb6644bd179af41bfc951e4bcf64fea6fdef71cb) - update your composer.json if you are using strict 2.0.0 - use ^2.0.0 for example.

**Comment by garethlawson** [comment]
Hi @arisro,

Thanks for looking into this.
I was having this same issue and updated to 2.0.1. That still didn't work, but I checked my composer.lock and it hadn't updated to the commit hash you referenced above, so I forced composer to update to that specific commit hash, and still, the issue persists. The conflict is now with the Symfony BrowserKit Client class, so I'm not even sure there's much you can do about this apart from refactoring to not use the trait?

Seems like the `Symfony\Component\BrowserKit\Client` class which your `LumenClient` class extends, and the `Laravel\Lumen\Testing\Concerns\MakesHttpRequests` Trait also aren't compatible because of the common $response property.

> [ErrorException]  
> Symfony\Component\BrowserKit\Client and Laravel\Lumen\Testing\Concerns\MakesHttpRequests define the same property ($response) in the composition of Arisro\Behat\Driver\LumenClient. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed...

Thanks again,
Gareth

**Comment by garethlawson** [comment]
Hi @arisro,

I have taken a good look at this and I am pretty sure this can only be solved in 1 of 4 ways:
1. To replace the parent class of the `LumenClient` class, i.e. the `Symfony\Component\BrowserKit\Client` class with some other, similar browser-kit class that does not contain the `$response` member.
2. To replace the `Laravel\Lumen\Testing\Concerns\MakesHttpRequests` Trait with a different Trait that does not contain `$response` member.
3. To refactor the `LumenClient` class to not extend from the `Symfony\Component\BrowserKit\Client` class by implementing it's functionality natively.
4. To refactor the `LumenClient` class to not use the `Laravel\Lumen\Testing\Concerns\MakesHttpRequests` trait, by implementing it's functionality natively.

None of these seem like ideal solutions, but I'm more inclined to replace the parent `Symfony\Component\BrowserKit\Client` class somehow, than the trait, because the trait is part of the Lumen core and I'm guessing it's critical to provide it's methods as part of the client. I had a look at some possible replacements for the `Symfony\Component\BrowserKit\Client` parent class, but I just want to make sure I'm not completely off the mark before putting too much effort into this.

I would like to help with this by submitting a PR if I can, but I'd like to get a bit of direction from you in terms of:
- what you think of these proposed solutions
- if you have a better idea for a solution
- or if you have some advice to point me in a better direction to create a suitable solution
